import { useEffect, useMemo, useState } from "react";
import { Logo } from "./Logo";

type Product = { _id: string; name: string; category: string; price: number; stock: number; status: string; imageKey?: string };
type Lead = { _id: string; name: string; company?: string; email: string; source: string; status: string; score?: number };
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
export function AdminPanel() {
  const [authed, setAuthed] = useState<boolean | null>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [tab, setTab] = useState<"overview" | "products" | "leads">("overview"); const [products, setProducts] = useState<Product[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [error, setError] = useState(""); const [name, setName] = useState("");
  const load = async () => { const me = await fetch("/api/admin/me", { credentials: "include" }); setAuthed(me.ok); if (!me.ok) return; const [p, l] = await Promise.all([fetch("/api/admin/products", { credentials: "include" }), fetch("/api/admin/leads", { credentials: "include" })]); setProducts((await p.json()).products ?? []); setLeads((await l.json()).leads ?? []); };
  useEffect(() => { void load(); }, []);
  const login = async (e: React.FormEvent) => { e.preventDefault(); const response = await fetch("/api/admin/login", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) return setError("Invalid credentials"); setError(""); await load(); };
  const addProduct = async (e: React.FormEvent) => { e.preventDefault(); const response = await fetch("/api/admin/products", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, category: "New collection", price: 0, stock: 0 }) }); if (!response.ok) return setError((await response.json()).error); setName(""); await load(); };
  const newLeads = leads.filter((lead) => lead.status === "new").length; const pipeline = leads.reduce((sum, lead) => sum + (lead.score ?? 0) * 1000, 0); const visible = useMemo(() => tab === "products" ? products : leads, [tab, products, leads]);
  if (authed === null) return <div className="p-10 text-sm">Loading admin…</div>;
  if (!authed) return <main className="flex min-h-screen items-center justify-center bg-[#F2EAD8] p-6"><form onSubmit={login} className="w-full max-w-sm rounded-2xl border border-[#e5e3dc] bg-[#F2EAD8] p-8"><Logo compact /><h1 className="mt-8 text-2xl font-semibold">Admin sign in</h1><p className="mt-2 text-sm text-[#5C4033]">Manage the GHEIR studio workspace.</p><input className="mt-7 w-full rounded-lg border p-3" type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} required /><input className="mt-3 w-full rounded-lg border p-3" type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} required /><button className="mt-5 w-full rounded-lg bg-[#2F3E34] p-3 font-medium text-white">Sign in</button>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}</form></main>;
  return <div className="min-h-screen bg-[#F2EAD8] text-[#2B2B2B]"><aside className="fixed inset-y-0 hidden w-64 border-r bg-[#F2EAD8] p-5 lg:block"><Logo compact /><nav className="mt-10 flex flex-col gap-2">{(["overview", "products", "leads"] as const).map((item) => <button className={`rounded-lg p-3 text-left capitalize ${tab === item ? "bg-[#2F3E34] text-white" : ""}`} onClick={() => setTab(item)} key={item}>{item === "leads" ? "Leads & inquiries" : item}</button>)}</nav></aside><main className="lg:pl-64"><header className="border-b bg-[#F2EAD8] p-6 flex justify-between"><h1 className="text-xl font-semibold">{tab === "overview" ? "Good morning" : tab === "products" ? "Products" : "Leads & inquiries"}</h1><button onClick={async () => { await fetch("/api/admin/logout", { method: "POST", credentials: "include" }); setAuthed(false); }} className="text-sm">Sign out</button></header><section className="mx-auto max-w-6xl p-6"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-[#F2EAD8] p-5"><p className="text-sm text-[#5C4033]">Products</p><strong className="text-3xl">{products.length}</strong></div><div className="rounded-xl border bg-[#F2EAD8] p-5"><p className="text-sm text-[#5C4033]">New leads</p><strong className="text-3xl">{newLeads}</strong></div><div className="rounded-xl border bg-[#F2EAD8] p-5"><p className="text-sm text-[#5C4033]">Pipeline value</p><strong className="text-3xl">{money(pipeline)}</strong></div></div>{tab === "products" && <form onSubmit={addProduct} className="my-8 flex gap-3"><input className="rounded-lg border p-3" placeholder="Product name" value={name} onChange={(e) => setName(e.target.value)} required /><button className="rounded-lg bg-[#2F3E34] px-4 text-white">Add product</button></form>}<div className="mt-8 rounded-xl border bg-[#F2EAD8] p-5">{tab === "products" ? <>{(visible as Product[]).map((p) => <div className="flex justify-between border-b py-4" key={p._id}><span>{p.name} <small className="text-[#5C4033]">{p.category}</small></span><span>{money(p.price)} · {p.stock} in stock</span></div>)}{!products.length && <p className="py-8 text-center text-sm text-[#5C4033]">No products yet.</p>}</> : tab === "leads" ? <>{(visible as Lead[]).map((lead) => <div className="flex justify-between border-b py-4" key={lead._id}><span>{lead.name} <small className="text-[#5C4033]">{lead.email}</small></span><span className="capitalize">{lead.status}</span></div>)}{!leads.length && <p className="py-8 text-center text-sm text-[#5C4033]">No leads yet.</p>}</> : <p className="text-sm text-[#5C4033]">Select Products or Leads & inquiries to manage records.</p>}</div></section></main></div>;
}
export default AdminPanel;
